import { PortfolioItemType } from "@/lib/types";

export const defaultPortfolioItems: PortfolioItemType[] = [
    {
        title: "The Hive Incubator's Website",
        slug: "hive-website",
        description: "The Hive Incubator in Akure, Nigeria, is a vibrant hub empowering entrepreneurs with the resources and support to transform ideas into thriving businesses. It fosters innovation and growth for startups at any stage.",
        longer_description: "As the director of Jowis Studio, I was responsible for leading a team of talented designers and developers to design and build the entire website for The Hive Incubator. This project involved working closely with the client to understand their vision and goals, and then translating that into a functional and visually appealing website. I managed the team's workflow, ensuring that tasks were completed on time and to a high standard. I also worked closely with the developers to ensure that the website was built with the latest technologies and best practices. The final result was a website that exceeded the client's expectations and helped to establish The Hive Incubator as a leading startup incubator in Nigeria.",
        link: "https://thehiveincubator.com/",
        stack: ["Next.js", "React", "JavaScript", "Tailwind CSS"],
        date: "2025",
        type: "Website",
        client: "The Hive Incubator",
        main_image: "/images/portfolio/hive/landing-page.png",
        other_images: [
            "/images/portfolio/hive/the-hub.png",
            "/images/portfolio/hive/the-team.png",
            "/images/portfolio/hive/the-entreprenuers.png",
            "/images/portfolio/hive/the-blogs.png",
            "/images/portfolio/hive/the-events.png",
            "/images/portfolio/hive/the-mentors.png",
        ],
        mock_up: "/images/portfolio/hive/mockup.png",
    },
    {
        title: "Anmut Website",
        slug: "anmut",
        description: "An estate and property development company that specialises in creating exceptional and sustainable real estate projects that meets the need of a modern society",
        longer_description: "As the director of Jowis Studio, I was responsible for leading a team of talented designers and developers to deliver exactly what Anmut wanted. I managed the team's workflow, ensuring that tasks were completed on time and to a high standard. I also worked closely with the developers to ensure that the website was built with the latest technologies and best practices. My experience in managing teams and projects helped me to ensure that the final product was of high quality and exceeded the client's expectations.",
        link: "https://www.anmutdevelopers.com/",
        stack: ["Next.js", "React", "JavaScript"],
        date: "2025",
        type: "Website",
        client: "Anmut Developers",
        main_image: "/images/portfolio/anmut/landing-page.png",
        other_images: [
            "/images/portfolio/anmut/the-services.png",
            "/images/portfolio/anmut/the-services-2.png",
            "/images/portfolio/anmut/the-team.png",
        ],
        mock_up: "/images/portfolio/anmut/mockup.png",
    },
    {
        title: "Square Farms's Website",
        slug: "farms-website",
        description: "Square Farms Africa is a forward-thinking agricultural enterprise. From poultry farming to innovative crop production techniques, we're building a sustainable future for agriculture.",
        longer_description: "At Jowis Studio, I led a talented team of designers and developers to build the website for Square Farms Africa. We worked closely together to ensure that the final product was of high quality and exceeded the client's expectations. My experience in managing teams and projects helped me to ensure that the final product was delivered on time and to a high standard.",
        link: "https://www.squarefarms.africa/",
        stack: ["Next.js", "React", "JavaScript"],
        date: "2025",
        type: "Website",
        client: "Square Farms Africa",
        main_image: "/images/portfolio/square-farms/landing-page.png",
        other_images: [
            "/images/portfolio/square-farms/the-commitment.png",
            "/images/portfolio/square-farms/the-contact.png",

        ],
        mock_up: "/images/portfolio/square-farms/mockup.png",
    },
];